services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

  mail:
    build:
      context: ./mail
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8082:8082"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/data/postgres

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8081:8081"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - user
    ports:
      - "8080:8080"

volumes:
  rabbitmq_data:
  rabbitmq_log:
  postgres-db:
