services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

  mail:
    build:
      context: ./mail
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8082:8082"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/data/postgres

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - mail
    ports:
      - "8081:8081"

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=password
    ports:
      - "6379:6379"

  mfa:
    build:
      context: ./mfa
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mail
    ports:
      - "8083:8083"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - user
      - mfa
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-db:/data

  file:
    build:
      context: ./file
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8084:8084"

volumes:
  rabbitmq_data:
  rabbitmq_log:
  postgres-db:
  mongo-db:
  azurite-db:
