// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: mfa.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MfaServiceClient is the client API for MfaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MfaServiceClient interface {
	GenerateOtp(ctx context.Context, in *GenerateOtpRequest, opts ...grpc.CallOption) (*OtpResponse, error)
	VerifyOtp(ctx context.Context, in *VerifyOtpRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
}

type mfaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMfaServiceClient(cc grpc.ClientConnInterface) MfaServiceClient {
	return &mfaServiceClient{cc}
}

func (c *mfaServiceClient) GenerateOtp(ctx context.Context, in *GenerateOtpRequest, opts ...grpc.CallOption) (*OtpResponse, error) {
	out := new(OtpResponse)
	err := c.cc.Invoke(ctx, "/mfa.MfaService/GenerateOtp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mfaServiceClient) VerifyOtp(ctx context.Context, in *VerifyOtpRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, "/mfa.MfaService/VerifyOtp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MfaServiceServer is the server API for MfaService service.
// All implementations must embed UnimplementedMfaServiceServer
// for forward compatibility
type MfaServiceServer interface {
	GenerateOtp(context.Context, *GenerateOtpRequest) (*OtpResponse, error)
	VerifyOtp(context.Context, *VerifyOtpRequest) (*VerifyResponse, error)
	mustEmbedUnimplementedMfaServiceServer()
}

// UnimplementedMfaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMfaServiceServer struct {
}

func (UnimplementedMfaServiceServer) GenerateOtp(context.Context, *GenerateOtpRequest) (*OtpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateOtp not implemented")
}
func (UnimplementedMfaServiceServer) VerifyOtp(context.Context, *VerifyOtpRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyOtp not implemented")
}
func (UnimplementedMfaServiceServer) mustEmbedUnimplementedMfaServiceServer() {}

// UnsafeMfaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MfaServiceServer will
// result in compilation errors.
type UnsafeMfaServiceServer interface {
	mustEmbedUnimplementedMfaServiceServer()
}

func RegisterMfaServiceServer(s grpc.ServiceRegistrar, srv MfaServiceServer) {
	s.RegisterService(&MfaService_ServiceDesc, srv)
}

func _MfaService_GenerateOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MfaServiceServer).GenerateOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mfa.MfaService/GenerateOtp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MfaServiceServer).GenerateOtp(ctx, req.(*GenerateOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MfaService_VerifyOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MfaServiceServer).VerifyOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mfa.MfaService/VerifyOtp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MfaServiceServer).VerifyOtp(ctx, req.(*VerifyOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MfaService_ServiceDesc is the grpc.ServiceDesc for MfaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MfaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mfa.MfaService",
	HandlerType: (*MfaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateOtp",
			Handler:    _MfaService_GenerateOtp_Handler,
		},
		{
			MethodName: "VerifyOtp",
			Handler:    _MfaService_VerifyOtp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mfa.proto",
}
